const UsersListTypes = {
  GET_USERS_LIST_START: "GET_USERS_LIST_START",
  GET_USERS_LIST_SUCCESS: "GET_USERS_LIST_SUCCESS",
  GET_USERS_LIST_FAILURE: "GET_USERS_LIST_FAILURE",
};

export default UsersListTypes;
