const GetAuthTokenTypes = {
  GET_AUTH_TOKEN_START: "GET_AUTH_TOKEN_START",
  GET_AUTH_TOKEN_SUCCESS: "GET_AUTH_TOKEN_SUCCESS",
  GET_AUTH_TOKEN_FAILURE: "GET_AUTH_TOKEN_FAILURE",
};

export default GetAuthTokenTypes;
