const UserDetailTypes = {
  GET_USER_DETAIL_START: "GET_USERS_DETAIL_START",
  GET_USER_DETAIL_SUCCESS: "GET_USERS_DETAIL_SUCCESS",
  GET_USER_DETAIL_FAILURE: "GET_USERS_DETAIL_FAILURE",
  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};

export default UserDetailTypes;
