const UserDetailTypes = {
  GET_USER_DETAIL_START: "GET_USERS_DETAIL_START",
  GET_USER_DETAIL_SUCCESS: "GET_USERS_DETAIL_SUCCESS",
  GET_USER_DETAIL_FAILURE: "GET_USERS_DETAIL_FAILURE",
};

export default UserDetailTypes;
